name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
     matrix:
      cfg:
      # For Ubuntu 18.04, the available compilers are specified according to
      # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
      - { os: ubuntu-18.04, cc: gcc-9, cxx: g++-9 } # 9.2.1
      - { os: ubuntu-18.04, cc: clang-9, cxx: clang++-9 } # 9.0.0
      # For Ubuntu 20.04, the available compilers are specified according to
      # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md
      - { os: ubuntu-20.04, cc: gcc-9, cxx: g++-9 } # 9.3.0
      - { os: ubuntu-20.04, cc: gcc-10, cxx: g++-10 } # 10.3.0
      - { os: ubuntu-20.04, cc: clang-10, cxx: clang++-10 } # 10.0.0
      - { os: ubuntu-20.04, cc: clang-11, cxx: clang++-11 } # 11.0.0
      - { os: ubuntu-20.04, cc: clang-12, cxx: clang++-12 } # 12.0.0
      # For macOS 10.15, the available compilers are specified according to
      # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
      - { os: macos-10.15, cc: gcc-9, cxx: g++-9 } # 9.3.0 Homebrew
    steps:
    - uses: actions/checkout@v2

    - name: Install googletest
      run: make -f makefile/Makefile.external CC=${{ matrix.cfg.cc }} CXX=${{ matrix.cfg.cxx }}

    - name: Run tests. 
      run: make -f makefile/Makefile.test CC=${{ matrix.cfg.cc }} CXX=${{ matrix.cfg.cxx }}