name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
     fail-fast: false
     matrix:
      cfg:
      # For Ubuntu 22.04, the available compilers are specified according to
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md
      - { os: ubuntu-22.04, cc: gcc-10, cxx: g++-10 } # 10.5.0
      - { os: ubuntu-22.04, cc: gcc-11, cxx: g++-11 } # 11.4.0
      - { os: ubuntu-22.04, cc: gcc-12, cxx: g++-12 } # 12.3.0
      - { os: ubuntu-22.04, cc: clang-13, cxx: clang++-13 } # 13.0.1
      - { os: ubuntu-22.04, cc: clang-14, cxx: clang++-14 } # 14.0.0
      - { os: ubuntu-22.04, cc: clang-15, cxx: clang++-15 } # 15.0.7
      # For Ubuntu 24.04, the available compilers are specified according to
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      - { os: ubuntu-24.04, cc: gcc-12, cxx: g++-12 } # 12.3.0
      - { os: ubuntu-24.04, cc: gcc-13, cxx: g++-13 } # 13.2.0
      - { os: ubuntu-24.04, cc: gcc-14, cxx: g++-14 } # 14.0.1
      - { os: ubuntu-24.04, cc: clang-16, cxx: clang++-16 } # 16.0.6
      - { os: ubuntu-24.04, cc: clang-17, cxx: clang++-17 } # 17.0.6
      - { os: ubuntu-24.04, cc: clang-18, cxx: clang++-18 } # 18.1.3
      # For macOS 12, the available compilers are specified according to
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
      #- { os: macos-12, cc: gcc-11, cxx: g++-11 } # 11.4.0 
      - { os: macos-12, cc: gcc-12, cxx: g++-12 } # 12.4.0 
      #- { os: macos-12, cc: gcc-13, cxx: g++-13 } # 13.3.0 
      - { os: macos-12, cc: gcc-14, cxx: g++-14 } # 14.1.0_2 
      # For macOS 13, the available compilers are specified according to
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
      #- { os: macos-13, cc: gcc-11, cxx: g++-11 } # 11.4.0 
      - { os: macos-13, cc: gcc-12, cxx: g++-12 } # 12.4.0 
      #- { os: macos-13, cc: gcc-13, cxx: g++-13 } # 13.3.0 
      - { os: macos-13, cc: gcc-14, cxx: g++-14 } # 14.1.0_2 
      # For macOS 13, the available compilers are specified according to
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
      #- { os: macos-14, cc: gcc-11, cxx: g++-11 } # 11.4.0 
      - { os: macos-14, cc: gcc-12, cxx: g++-12 } # 12.4.0 
      - { os: macos-14, cc: gcc-13, cxx: g++-13 } # 13.3.0 
      - { os: macos-14, cc: gcc-14, cxx: g++-14 } # 14.1.0_2 

    steps:
    - uses: actions/checkout@v2

    - name: Install googletest
      run: make -f makefile/Makefile.external CC=${{ matrix.cfg.cc }} CXX=${{ matrix.cfg.cxx }}

    - name: Run tests. 
      run: make -f makefile/Makefile.test CC=${{ matrix.cfg.cc }} CXX=${{ matrix.cfg.cxx }}